apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm-histogram-eq.fullname" . }}-pvc
  labels:
    app.kubernetes.io/name: {{ include "helm-histogram-eq.name" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size }}
