import pytest
import asyncio
import os
import cv2
import numpy as np
import httpx
from httpx import ASGITransport

from main import app, UPLOAD_DIR_STR

# Use the real test data
TEST_IMAGE = "unequalized_dog.jpg"

@pytest.mark.asyncio
async def test_end_to_end_local_processing():
    # Ensure source image exists
    original_file_path = os.path.join(UPLOAD_DIR_STR, TEST_IMAGE)
    assert os.path.exists(original_file_path), f"Test image {TEST_IMAGE} missing from shared_data"
    
    # 1. Test Node Listing (Expected 0 since no workers connected here)
    async with httpx.AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        response = await client.get("/nodes")
        assert response.status_code == 200
        assert len(response.json()["connected_workers"]) == 0

    expected_out = os.path.join(UPLOAD_DIR_STR, f"unequalized_dog_equalized.jpg")
    
    # Clean up any existing equalized file from previous runs BEFORE starting the job
    if os.path.exists(expected_out):
        os.remove(expected_out)

    # 2. Trigger processing job via BackgroundTasks
    async with httpx.AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        response = await client.post(f"/process/{TEST_IMAGE}")
        assert response.status_code == 200
        assert "job_id" in response.json()

    # Yield control to allow BackgroundTasks (distribute_job) to finish (local processing fallback)
    for _ in range(20):  # wait up to 2 seconds
        await asyncio.sleep(0.1)
        if os.path.exists(expected_out):
            break
            
    assert os.path.exists(expected_out), "Equalized file was not generated by local fallback."

    # Verify the image was actually processed
    img_orig = cv2.imread(original_file_path, cv2.IMREAD_GRAYSCALE)
    img_eq = cv2.imread(expected_out, cv2.IMREAD_GRAYSCALE)
    assert not np.array_equal(img_eq, img_orig), "Equalized output is identical to original image."

    # 3. Test /files/equalized endpoints
    async with httpx.AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        response = await client.get("/files/equalized")
        assert response.status_code == 200
        files = [f["name"] for f in response.json()["files"]]
        assert os.path.basename(expected_out) in files

    # 4. Test downloading the result
    async with httpx.AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        response = await client.get(f"/download/unequalized_dog_equalized.jpg")
        assert response.status_code == 200

    # Do not clean up the test generated image to let humans view it if needed, or we just clean the _equalized one
    os.remove(expected_out)
